django/week4/portfolio/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path(r'resume/', include('resume.urls' , namespace = 'resume')),
    path(r'portfolio/', views.portfolio, name='portfolio'),
    path(r'contact/', views.contact, name='contact'),
    path(r'admin/', admin.site.urls),
]

django/week4/resume/urls.py
from django.urls import path

from . import views

app_name = 'resume'
urlpatterns = [
    path(r'index/', views.index, name='index'),
]

django/week4/resume/models.py
from django.db import models
from django.forms import ModelForm

class Resume(models.Model):
    """
    Model (DB layer) for "resume" app
    Parent Key: id
    """
    First_name = models.CharField(max_length=40, null=False, blank=True)
    Last_name = models.CharField(max_length=40, null=False, blank=True)


    def get_full_name(self):
        """
        Model.methods
        Returns the persons full name
        """
        return "{} {}".format(self.First_name, self.Last_name)


    def get_last_name_first_name(self):
        """
        Model.methods
        Returns the persons full name, Last name first
        """
        return "{} {}".format(self.Last_name, self.First_name)


    def get_experience(self):
        """
        Model.methods
        Returns the foreign key related to "Experience" objects
        """
        return self.experience_set.all()


    def get_education(self):
        """
        Model.methods
        Returns the foreign key related to "Education" objects
        """
        return  self.education_set.all()



class Experience(models.Model):
    """
    Model (DB layer) for "resume" app that hold Experience records
    ForeignKey: Resume
    """
    parent_resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default =1)
    company = models.CharField(max_length=40, null=False, blank=True)
    title = models.CharField(max_length=40, null=False, blank=True)
    location = models.CharField(max_length=40, null=False, blank=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null =True)
    description = models.TextField()

    def __str__(self):
        return self.title

class Education(models.Model):
    """
    Model (DB layer) for "resume" app that hold Education records
    ForeignKey: Resume
    """
    parent_resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default =1)
    institution_name = models.CharField(max_length=40, null=False, blank=True)
    location = models.CharField(max_length=40 , null=False, blank=True)
    degree = models.CharField(max_length=40, null=False, blank=True)
    major = models.CharField(max_length=40, null=False, blank=True)
    gpa = models.FloatField(max_length=40, null=False, blank=True)

    def __str__(self):
        return self.institution_name

django/week4/portfolio/views.py
from django.shortcuts import render

def home(request):
    """
    Renders the home page for the web application portfolio "Andrea Murphy"
    Retuns: the home.html page
    """
    context = {}
    return render(request, 'home.html', context)

def portfolio(request):
    """
    Renders my Portfolio static page template
    Retuns: the portfolio.html page
    """
    context = {}
    return render(request, 'portfolio.html', context)


def contact(request):
    """
    Renders my Contact static page template
    Retuns: the contact.html page
    """
    context = {}
    return render(request, 'contact.html', context)

django/week4/resume/views.py
from django.shortcuts import render
from django.template import loader

from .models import Resume

def index(request):
    """
    Renders the Resume app home template
    Context: Education in query set
    Returns: 'resume/home.html'
    """

    resume = Resume.objects.first()

    context = { 'resume':resume }
    return render(request, 'resume/home.html', context)

django/week4/resume/templates/resume/home.html
{% extends 'base.html' %}
{% block content %}
  <div class='resume-banner'>
          {{ resume.get_full_name }}
  </div>
            <hr>
       <div class='resume-subbanner'>
            <h2>Experience</h2>
            <hr>
      </div>
      <section class='blocks'>
                {% for experience in resume.get_experience %}
                        <h3>{{experience.company}}</h3>
                        <h4>{{experience.title}}</h4>
                        {{experience.location}}<br>
                        {{experience.start_date}}<br>
                        {{experience.end_date}}
                        <p>{{experience.description}}</p>
                         {% endfor %}
      </section>
       <div class='resume-subbanner'>
            <h2>Education</h2>
            <hr>
      </div>
      <section class='blocks'>
            {% for education in resume.get_education %}
                  <h3>{{ education.institution_name }}</h3>
                  <h4>{{ education.location }}</h4>
                           {{ education.degree }}
                           {{ education.major }}<br>
                            {{ education.gpa }}
                      {% endfor %}
      </section>
  {% endblock %}
    </div>
    </div>
  </div>
</div>

django/week4/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Andrea Murphy</title>
    <link rel='stylesheet' href="{% static 'css/style.css' %}" />
  </head>
  <body>
      <nav>
        <a href="{% url 'home' %}">Home Page</a> |
        <a href="{% url 'resume:index' %}">Resume</a> |
        <a href="{% url 'portfolio' %}">Portfolio</a> |
        <a href="{% url 'contact' %}">Contact</a> |
      </nav>

      {% block content %}
      {% endblock %}

  </body>
</html>

django/week4/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class='contact-banner'>
        <div id='wrap'>
            <h1>Contact Information</h1>
            <hr>
        </div>
    </div>
        <section class='contact-content'>
                <h1><a href="mailto:andrealindamurphy@gmail.com" target="_blank">Email</a></h1>
                <hr>
                <h1><a href="https://www.linkedin.com/in/andrealindamurphy/" target="_blank">Likendin</a></h1>
            </section>
        </div>
 </div>
{% endblock %}

django/week4/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class='homepage-banner'>
              <h1>Andrea L. Murphy</h1>
              <hr>
    <i class='homepage-content'>
              <i>University of New Hampshire<br>Information Technology, M.S.</i>
      </div>
</div>
</div>
{% endblock %}

django/week4/templates/portfolio.html
{% extends 'base.html' %}

{% block content %}
    <div class='portfolio-banner'>
            <div id='wrap'>
                <h1>Portfolio
            </h1>
        </div>
    </div>
                <hr>

    <div class ='row'>
            <div class='column'>
                        <h2><u>Website Design and Development</u></h2>
                        <h1><a href="https://www.bpdvideo.com/" target="_blank">BPDvideo.com</a></h1>
                        <h1><a href="https://www.myfloatzone.com/" target="_blank">Float Zone</a></h1>
                        <h1><a href ="https:/lampros.chaidas.com/post/Compression-examples/" target="_blank">Squirrel5:Linux Administration Services</a></h1>
             </div>
    <div class ='column'>
                <h2><u>Django Web Application Projects</u></h2>
                       <div class= 'img-thumbnail'>
                            <img src= 'User/andreamurphy/workspace/django/week2/static/media/damus.JPG' >
                        </div>
                    </div>
    <div class ='row'>
            <div class='column'>
                        <h2><u>Graphic Design</u></h2>
             </div>
    <div class ='column'>
                <h2><u>Current Projects</u></h2>
                <h1><a href="https://github.com/andrea5972" target="_blank">GitHub</a></h1>
                    <p></p>
        </div>
    </div>
{% endblock %}